<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aritz Adin">

<title>Práctica 3: Contrastes de hipótesis y análisis de la varianza – BIOEST 2025-26</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BIOEST 2025-26</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica0.html"> 
<span class="menu-text">Práctica 0</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica1.html"> 
<span class="menu-text">Práctica 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica2.html"> 
<span class="menu-text">Práctica 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Practica3.html" aria-current="page"> 
<span class="menu-text">Práctica 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica4.html"> 
<span class="menu-text">Práctica 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica5.html"> 
<span class="menu-text">Práctica 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica6.html"> 
<span class="menu-text">Práctica 6</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Practica7.html"> 
<span class="menu-text">Práctica 7</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PracticaRepaso.html"> 
<span class="menu-text">Práctica Repaso</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#descripción" id="toc-descripción" class="nav-link active" data-scroll-target="#descripción">Descripción</a>
  <ul class="collapse">
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  </ul></li>
  <li><a href="#contrastes-paramétricos" id="toc-contrastes-paramétricos" class="nav-link" data-scroll-target="#contrastes-paramétricos">1. Contrastes paramétricos</a>
  <ul class="collapse">
  <li><a href="#contrasta-al-nivel-de-significación-0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200.-justifica-si-puedes-asumir-normalidad" id="toc-contrasta-al-nivel-de-significación-0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200.-justifica-si-puedes-asumir-normalidad" class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200.-justifica-si-puedes-asumir-normalidad">1.1. Contrasta al nivel de significación 0.05 si el nivel medio de colesterol en los hombres del condado de Buckingham es superior a 200. Justifica si puedes asumir normalidad</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.-comprueba-que-las-dos-muestras-provienen-de-poblaciones-normales.-realiza-el-correspondiente-test-de-medias." id="toc-contrasta-al-nivel-de-significación-0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.-comprueba-que-las-dos-muestras-provienen-de-poblaciones-normales.-realiza-el-correspondiente-test-de-medias." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.-comprueba-que-las-dos-muestras-provienen-de-poblaciones-normales.-realiza-el-correspondiente-test-de-medias.">1.2. Contrasta al nivel de significación 0.10 si la presión diastólica media de los hombres es distinta a la presión diastólica media de las mujeres. Comprueba que las dos muestras provienen de poblaciones normales. Realiza el correspondiente test de medias.</a></li>
  <li><a href="#se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2." id="toc-se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2." class="nav-link" data-scroll-target="#se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2.">1.3. Se dispone de dos aparatos, uno nuevo y otro antiguo, para medir los niveles de glucosa en sangre. Los médicos sospechan que el nuevo aparato proporciona niveles de glucosa en sangre superiores al antiguo. Se dispone de una muestra con 15 pacientes diabéticos a los que se les ha medido los niveles de glucosa con los dos aparatos. Las medidas se encuentran en el fichero <code>GLUCOSE</code> de la librería <code>PASWR2</code>.</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2." id="toc-contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2.">1.4. Contrasta al nivel de significación 0.05 si la proporción de hombres con hemoglobina glicosilada (<code>glyhb</code>) por encima del 6% es superior a 0.2.</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl." id="toc-contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl.">1.5. Contrasta al nivel de significación 0.05 si la proporción de hombres con colesterol por debajo de 200mg/dL es superior a la proporción de mujeres con colesterol por debajo de 200mg/dL.</a></li>
  </ul></li>
  <li><a href="#contrastes-no-paramétricos" id="toc-contrastes-no-paramétricos" class="nav-link" data-scroll-target="#contrastes-no-paramétricos">2. Contrastes no-paramétricos</a>
  <ul class="collapse">
  <li><a href="#puede-asumirse-que-la-variable-hdl-en-mujeres-sigue-una-distribución-normal-contrasta-al-nivel-de-significación-0.05-si-la-media-de-la-variable-hdl-en-mujeres-es-superior-a-47." id="toc-puede-asumirse-que-la-variable-hdl-en-mujeres-sigue-una-distribución-normal-contrasta-al-nivel-de-significación-0.05-si-la-media-de-la-variable-hdl-en-mujeres-es-superior-a-47." class="nav-link" data-scroll-target="#puede-asumirse-que-la-variable-hdl-en-mujeres-sigue-una-distribución-normal-contrasta-al-nivel-de-significación-0.05-si-la-media-de-la-variable-hdl-en-mujeres-es-superior-a-47.">2.1. ¿Puede asumirse que la variable ‘hdl’ en mujeres sigue una distribución normal? Contrasta al nivel de significación 0.05 si la media de la variable ‘hdl’ en mujeres es superior a 47.</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-entre-los-niveles-de-hdl-en-hombres-y-en-mujeres.-comprueba-si-puede-asumirse-normalidad-y-realiza-el-contraste-adecuado." id="toc-contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-entre-los-niveles-de-hdl-en-hombres-y-en-mujeres.-comprueba-si-puede-asumirse-normalidad-y-realiza-el-contraste-adecuado." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-entre-los-niveles-de-hdl-en-hombres-y-en-mujeres.-comprueba-si-puede-asumirse-normalidad-y-realiza-el-contraste-adecuado.">2.2. ¿Contrasta al nivel de significación 0.05 si existen diferencias entre los niveles de hdl en hombres y en mujeres. Comprueba si puede asumirse normalidad y realiza el contraste adecuado.</a></li>
  <li><a href="#considera-el-fichero-phenyl-de-la-libreria-paswr2.-contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-en-los-niveles-medios-de-la-coenzima-q10-en-el-momento-de-comenzar-el-estudio-variable-q10.1-y-al-finalizar-el-estudio-variable-q10.4." id="toc-considera-el-fichero-phenyl-de-la-libreria-paswr2.-contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-en-los-niveles-medios-de-la-coenzima-q10-en-el-momento-de-comenzar-el-estudio-variable-q10.1-y-al-finalizar-el-estudio-variable-q10.4." class="nav-link" data-scroll-target="#considera-el-fichero-phenyl-de-la-libreria-paswr2.-contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-en-los-niveles-medios-de-la-coenzima-q10-en-el-momento-de-comenzar-el-estudio-variable-q10.1-y-al-finalizar-el-estudio-variable-q10.4.">2.3. Considera el fichero <code>PHENYL</code> de la libreria <code>PASWR2</code>. Contrasta al nivel de significación 0.05 si existen diferencias en los niveles medios de la coenzima Q10 en el momento de comenzar el estudio (variable <code>Q10.1</code>) y al finalizar el estudio (variable <code>Q10.4</code>).</a></li>
  </ul></li>
  <li><a href="#análisis-de-la-varianza-y-test-de-kruskal-wallis" id="toc-análisis-de-la-varianza-y-test-de-kruskal-wallis" class="nav-link" data-scroll-target="#análisis-de-la-varianza-y-test-de-kruskal-wallis">3. Análisis de la varianza y test de Kruskal-Wallis</a>
  <ul class="collapse">
  <li><a href="#contrasta-al-nivel-de-significación-0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres." id="toc-contrasta-al-nivel-de-significación-0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres.">3.1. Contrasta al nivel de significación 0.10 si el tamaño del cuerpo (<code>frame</code>) influye en la presión diastólica (<code>bp.1d</code>) de las mujeres.</a></li>
  <li><a href="#utiliza-el-fichero-diabetes.female-para-responder-a-las-siguientes-cuestiones." id="toc-utiliza-el-fichero-diabetes.female-para-responder-a-las-siguientes-cuestiones." class="nav-link" data-scroll-target="#utiliza-el-fichero-diabetes.female-para-responder-a-las-siguientes-cuestiones.">3.2. Utiliza el fichero <code>diabetes.female</code> para responder a las siguientes cuestiones.</a></li>
  </ul></li>
  <li><a href="#para-entregar" id="toc-para-entregar" class="nav-link" data-scroll-target="#para-entregar">4. Para entregar</a>
  <ul class="collapse">
  <li><a href="#contrasta-al-nivel-de-significación-0.1-si-los-niveles-medios-de-la-concentración-de-interleukina-6-il6-son-significativamente-distintos-en-pacientes-con-cáncer-en-estadio-i-que-en-paciente-con-cáncer-en-estadio-ii." id="toc-contrasta-al-nivel-de-significación-0.1-si-los-niveles-medios-de-la-concentración-de-interleukina-6-il6-son-significativamente-distintos-en-pacientes-con-cáncer-en-estadio-i-que-en-paciente-con-cáncer-en-estadio-ii." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-0.1-si-los-niveles-medios-de-la-concentración-de-interleukina-6-il6-son-significativamente-distintos-en-pacientes-con-cáncer-en-estadio-i-que-en-paciente-con-cáncer-en-estadio-ii.">4.1. Contrasta al nivel de significación 0.1 si los niveles medios de la concentración de Interleukina-6 (<code>IL6</code>) son significativamente distintos en pacientes con cáncer en estadio I que en paciente con cáncer en estadio II.</a></li>
  <li><a href="#se-estudió-la-eficacia-de-la-sulfinpirazona-en-prevenir-la-muerte-después-de-sufrir-infarto-de-miocardio.-para-ello-se-consideraron-pacientes-que-habían-sufrido-infarto-de-miocardio.-a-un-grupo-se-les-proporcionó-sulfinpirazona-y-a-otro-grupo-se-les-suministró-placebo.-en-la-siguiente-tabla-se-muestra-el-número-de-pacientes-de-cada-grupo-que-murieron-y-que-superaron-el-infarto." id="toc-se-estudió-la-eficacia-de-la-sulfinpirazona-en-prevenir-la-muerte-después-de-sufrir-infarto-de-miocardio.-para-ello-se-consideraron-pacientes-que-habían-sufrido-infarto-de-miocardio.-a-un-grupo-se-les-proporcionó-sulfinpirazona-y-a-otro-grupo-se-les-suministró-placebo.-en-la-siguiente-tabla-se-muestra-el-número-de-pacientes-de-cada-grupo-que-murieron-y-que-superaron-el-infarto." class="nav-link" data-scroll-target="#se-estudió-la-eficacia-de-la-sulfinpirazona-en-prevenir-la-muerte-después-de-sufrir-infarto-de-miocardio.-para-ello-se-consideraron-pacientes-que-habían-sufrido-infarto-de-miocardio.-a-un-grupo-se-les-proporcionó-sulfinpirazona-y-a-otro-grupo-se-les-suministró-placebo.-en-la-siguiente-tabla-se-muestra-el-número-de-pacientes-de-cada-grupo-que-murieron-y-que-superaron-el-infarto.">4.2. Se estudió la eficacia de la sulfinpirazona en prevenir la muerte después de sufrir infarto de miocardio. Para ello se consideraron pacientes que habían sufrido infarto de miocardio. A un grupo se les proporcionó sulfinpirazona y a otro grupo se les suministró placebo. En la siguiente tabla se muestra el número de pacientes de cada grupo que murieron y que superaron el infarto.</a></li>
  <li><a href="#contrasta-al-nivel-de-significación-alpha0.1-si-existen-diferencias-en-la-edad-media-de-los-pacientes-según-el-estadio-de-cancer-cancerstage." id="toc-contrasta-al-nivel-de-significación-alpha0.1-si-existen-diferencias-en-la-edad-media-de-los-pacientes-según-el-estadio-de-cancer-cancerstage." class="nav-link" data-scroll-target="#contrasta-al-nivel-de-significación-alpha0.1-si-existen-diferencias-en-la-edad-media-de-los-pacientes-según-el-estadio-de-cancer-cancerstage.">4.3. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.1\)</span> si existen diferencias en la edad media de los pacientes según el estadio de cancer (<code>CancerStage</code>).</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Práctica 3: Contrastes de hipótesis y análisis de la varianza</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aritz Adin </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">29/10/2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="descripción" class="level1">
<h1>Descripción</h1>
<p>En esta práctica vamos a trabajar con el fichero de datos <code>Diabetes</code>.</p>
<ul>
<li><p>El fichero de datos contiene 19 variables medidas sobre 403 pacientes. Estos pacientes forman parte de un estudio con 1046 sujetos diseñado para investigar la prevalencia de la de obesidad, diabetes, y otros factores de riesgo cardiovasculares para Afroamericanos en Virginia, EEUU.</p></li>
<li><p>Según Dr John Hong, Diabetes Mellitus Tipo II está asociada con la obesidad. El índice cintura-cadera puede ser un predictor en diabetes y enfermedades de corazón.</p></li>
<li><p>Diabetes Mellitus Tipo II está también asociada con hipertensión y ambos pueden ser parte del “Síndrome X”.</p></li>
<li><p>Los 403 sujetos del estudio son aquellos a los que se les hizo un seguimiento de diabetes. La hemoglobina glicosilada <span class="math inline">\(&gt;7.0\)</span> se toma normalmente como diagnóstico positivo de diabetes.</p></li>
</ul>
<p>El fichero puede descargarse de la web <a href="http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets" class="uri">http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets</a></p>
<p>Para más información ver el paper</p>
<p>Willems JP, Saunders JT, DE Hunt, JB Schorling. Prevalence of coronary heart disease risk factors among rural blacks: A community-based study. <em>Southern Medical Journal</em> 90:814-820; 1997. <a href="https://europepmc.org/abstract/med/9258308" class="uri">https://europepmc.org/abstract/med/9258308</a></p>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>Estas son las variables que contiene el fichero (se han eliminado alguna del fichero original y se han reemplazado algunos valores perdidos):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>id</code></td>
<td>Subject ID</td>
</tr>
<tr class="even">
<td><code>chol</code></td>
<td>Total Cholesterol (mg/dL)</td>
</tr>
<tr class="odd">
<td><code>stab.glu</code></td>
<td>Stabilized Glucose (mg/dL)</td>
</tr>
<tr class="even">
<td><code>hdl</code></td>
<td>High Density Lipoprotein (mg/dL)</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Cholesterol / HDL ratio</td>
</tr>
<tr class="even">
<td><code>glyhb</code></td>
<td>Glycolsolated Hemoglobin (%)</td>
</tr>
<tr class="odd">
<td><code>location</code></td>
<td>Buckingham or Louisa</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>Age of patient (years)</td>
</tr>
<tr class="odd">
<td><code>gender</code></td>
<td>Male or Female</td>
</tr>
<tr class="even">
<td><code>height</code></td>
<td>Height (inches)</td>
</tr>
<tr class="odd">
<td><code>weight</code></td>
<td>Weight (pounds)</td>
</tr>
<tr class="even">
<td><code>frame</code></td>
<td>Body frame size (small, medium, large)</td>
</tr>
<tr class="odd">
<td><code>bp.1s</code></td>
<td>First Systolic Blood Pressure (mmHg)</td>
</tr>
<tr class="even">
<td><code>bp.1d</code></td>
<td>First Diastolic Blood Pressure (mmHg)</td>
</tr>
<tr class="odd">
<td><code>waist</code></td>
<td>Waistline (inches)</td>
</tr>
<tr class="even">
<td><code>hip</code></td>
<td>Hip measurement (inches)</td>
</tr>
</tbody>
</table>
<p><strong>Para leer el fichero de diabetes en <code>R</code>:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>diabetes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"diabetes.txt"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">sep=</span><span class="st">""</span>, <span class="at">dec=</span><span class="st">"."</span>, <span class="at">stringsAsFactors=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    id chol stab.glu hdl ratio glyhb   location age gender height weight  frame
1 1000  203       82  56   3.6  4.31 Buckingham  46 female     62    121 medium
2 1001  165       97  24   6.9  4.44 Buckingham  29 female     64    218  large
3 1002  228       92  37   6.2  4.64 Buckingham  58 female     61    256  large
4 1003   78       93  12   6.5  4.63 Buckingham  67   male     67    119  large
5 1005  249       90  28   8.9  7.72 Buckingham  64   male     68    183 medium
6 1008  248       94  69   3.6  4.81 Buckingham  34   male     71    190  large
  bp.1s bp.1d waist hip
1   118    59    29  38
2   112    68    46  48
3   190    92    49  57
4   110    50    33  38
5   138    80    44  41
6   132    86    36  42</code></pre>
</div>
</div>
<p><strong>IMPORTANTE:</strong></p>
<ul>
<li><p>Contraste bilateral –&gt; <code>alternative="two.sided"</code></p></li>
<li><p>Contraste unilateral inferior –&gt; <code>alternative="less"</code></p></li>
<li><p>Contraste unilateral superior –&gt; <code>alternative="greater"</code></p></li>
</ul>
</section>
</section>
<section id="contrastes-paramétricos" class="level1">
<h1>1. Contrastes paramétricos</h1>
<section id="contrasta-al-nivel-de-significación-0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200.-justifica-si-puedes-asumir-normalidad" class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.05-si-el-nivel-medio-de-colesterol-en-los-hombres-del-condado-de-buckingham-es-superior-a-200.-justifica-si-puedes-asumir-normalidad">1.1. Contrasta al nivel de significación 0.05 si el nivel medio de colesterol en los hombres del condado de Buckingham es superior a 200. Justifica si puedes asumir normalidad</h2>
<p>Sea X=“Nivel de colesterol de los hombres del condado de Buckingham (mg/dL)”.</p>
<p>El contraste que debemos realizar (<span class="math inline">\(\alpha=0.05\)</span>) se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \mu=200 \\
H_1: &amp; \mu&gt;200 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>En primer lugar seleccionamos los datos de la muestra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pos <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>location<span class="sc">==</span><span class="st">"Buckingham"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>chol.manB <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>chol[pos]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Comprobamos la condición de normalidad (test de Shapiro-Wilks):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PASWR2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(chol.manB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
  86.000    0.000   78.000  174.000  203.603  197.500  202.536  230.750 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 347.000   44.598 1988.956    4.809   56.750  269.000    0.677    0.402 
SW p-val 
   0.208 </code></pre>
</div>
</div>
<p>Realizamos el test (paramétrico) para una media:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chol.manB, <span class="at">mu=</span><span class="dv">200</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  chol.manB
t = 0.74918, df = 85, p-value = 0.2279
alternative hypothesis: true mean is greater than 200
95 percent confidence interval:
 195.6054      Inf
sample estimates:
mean of x 
 203.6029 </code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.23&gt;\alpha=0.05 \Rightarrow\)</span> No rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, no existen evidencias estadísticas para afirmar que el nivel medio de colesterol en los hombres de Buckingham es superior a 200 mg/dL.</p>
</section>
<section id="contrasta-al-nivel-de-significación-0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.-comprueba-que-las-dos-muestras-provienen-de-poblaciones-normales.-realiza-el-correspondiente-test-de-medias." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.10-si-la-presión-diastólica-media-de-los-hombres-es-distinta-a-la-presión-diastólica-media-de-las-mujeres.-comprueba-que-las-dos-muestras-provienen-de-poblaciones-normales.-realiza-el-correspondiente-test-de-medias.">1.2. Contrasta al nivel de significación 0.10 si la presión diastólica media de los hombres es distinta a la presión diastólica media de las mujeres. Comprueba que las dos muestras provienen de poblaciones normales. Realiza el correspondiente test de medias.</h2>
<p>Definimos las variables:</p>
<p>X=“Presión diastólica de los hombres (mmHg)”</p>
<p>Y=“Presión diastólica de las mujeres (mmHg)”</p>
<p>El contraste que debemos realizar (<span class="math inline">\(\alpha=0.10\)</span>) se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \mu_X - \mu_Y = 0 \\
H_1: &amp; \mu_X - \mu_Y \neq 0 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>En primer lugar seleccionamos los datos de las muestras:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># table(diabetes$gender)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>pos1 <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>bp1d.male <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>bp<span class="fl">.1</span>d[pos1]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pos2 <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>bp1d.female <span class="ot">&lt;-</span>diabetes<span class="sc">$</span>bp<span class="fl">.1</span>d[pos2]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Comprobamos la condición de normalidad en ambas variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(bp1d.male)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 169.000    0.000   50.000   76.000   84.465   82.000   84.200   92.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 122.000   13.504  182.347    1.039   16.000   72.000    0.124    0.351 
SW p-val 
   0.058 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(bp1d.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 234.000    0.000   48.000   72.000   82.496   82.000   82.269   90.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 124.000   13.474  181.535    0.881   18.000   76.000   -0.014    0.216 
SW p-val 
   0.232 </code></pre>
</div>
</div>
<p>Verificamos si podemos asumir que las varianzas son iguales o no:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bp1d.male, bp1d.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># boxplot(bp.1d ~ gender, data=diabetes)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Realizamos el test (paramétrico) para la diferencia de medias en poblaciones independientes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bp1d.male, bp1d.female, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  bp1d.male and bp1d.female
t = 1.4469, df = 401, p-value = 0.1487
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.7066209  4.6461575
sample estimates:
mean of x mean of y 
 84.46534  82.49558 </code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.15&gt;\alpha=0.10 \Rightarrow\)</span> No rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 10%, no existen evidencias estadísticas para afirmar que la presión diastólica media de los hombres sea distinta del de las mujeres.</p>
</section>
<section id="se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2." class="level2">
<h2 class="anchored" data-anchor-id="se-dispone-de-dos-aparatos-uno-nuevo-y-otro-antiguo-para-medir-los-niveles-de-glucosa-en-sangre.-los-médicos-sospechan-que-el-nuevo-aparato-proporciona-niveles-de-glucosa-en-sangre-superiores-al-antiguo.-se-dispone-de-una-muestra-con-15-pacientes-diabéticos-a-los-que-se-les-ha-medido-los-niveles-de-glucosa-con-los-dos-aparatos.-las-medidas-se-encuentran-en-el-fichero-glucose-de-la-librería-paswr2.">1.3. Se dispone de dos aparatos, uno nuevo y otro antiguo, para medir los niveles de glucosa en sangre. Los médicos sospechan que el nuevo aparato proporciona niveles de glucosa en sangre superiores al antiguo. Se dispone de una muestra con 15 pacientes diabéticos a los que se les ha medido los niveles de glucosa con los dos aparatos. Las medidas se encuentran en el fichero <code>GLUCOSE</code> de la librería <code>PASWR2</code>.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"GLUCOSE"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(GLUCOSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  patient    old    new
1       1 182.47 195.64
2       2 175.53 196.31
3       3 181.71 190.33
4       4 179.03 192.90
5       5 177.28 193.24
6       6 177.49 193.05</code></pre>
</div>
</div>
<p>Definimos las variables:</p>
<p>X=“Nivel de glucosa (mg/dL) con el aparato viejo”</p>
<p>Y=“Nivel de glucosa (mg/dL) con el aparato nuevo”</p>
<ul>
<li><strong>¿Son las muestras independientes?</strong></li>
</ul>
<p>Como se tratan de los mismos individuos medidos en distintos instantes de tiempo, las muestras son dependientes (o emparejadas). Por lo tanto, trabajaremos con la diferencia entre ambas variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> GLUCOSE<span class="sc">$</span>old <span class="sc">-</span> GLUCOSE<span class="sc">$</span>new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Comprueba si puede asumirse la hipótesis de normalidad.</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(D)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
  15.000    0.000  -20.780  -16.085  -14.560  -14.330  -14.560  -12.830 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
  -8.620    3.253   10.582    0.840    3.255   12.160   -0.677   -0.105 
SW p-val 
   0.994 </code></pre>
</div>
</div>
<ul>
<li><strong>Contrasta al nivel de significación</strong> <span class="math inline">\(\alpha=0.05\)</span> <strong>si el nuevo aparato proporciona medidas más altas que el antiguo.</strong></li>
</ul>
<p>El contraste que debemos realizar se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \mu_D = 0 \\
H_1: &amp; \mu_D &lt; 0 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>Como se verifica la hipótesis de normalidad, realizamo el test (paramétrico) para una media:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(D, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  D
t = -17.335, df = 14, p-value = 3.701e-11
alternative hypothesis: true mean is less than 0
95 percent confidence interval:
      -Inf -13.08064
sample estimates:
mean of x 
   -14.56 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Otra opción:</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(GLUCOSE<span class="sc">$</span>old, GLUCOSE<span class="sc">$</span>new, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  GLUCOSE$old and GLUCOSE$new
t = -17.335, df = 14, p-value = 3.701e-11
alternative hypothesis: true mean difference is less than 0
95 percent confidence interval:
      -Inf -13.08064
sample estimates:
mean difference 
         -14.56 </code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(\approx 0&lt;\alpha=0.05 \Rightarrow\)</span> Rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, existen evidencias estadísticas para afirmar que el aparato nuevo proporciona niveles de medios de glucosa en sangre superiores al aparato viejo.</p>
</section>
<section id="contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-hemoglobina-glicosilada-glyhb-por-encima-del-6-es-superior-a-0.2.">1.4. Contrasta al nivel de significación 0.05 si la proporción de hombres con hemoglobina glicosilada (<code>glyhb</code>) por encima del 6% es superior a 0.2.</h2>
<p>Definimos la variable:</p>
<p>X=“Nº de hombres con valores de hemoglobina glicosilada superior al 6%” <span class="math inline">\(\sim Bin(n,\pi)\)</span></p>
<ul>
<li><strong>Calcula el número de hombres en la muestra con <code>glyhb</code> por encima del 6% y el total de hombres en la muestra.</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Casos favorables</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>glyhb<span class="sc">&gt;</span><span class="dv">6</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Casos totales</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 169</code></pre>
</div>
</div>
<ul>
<li><strong>Realiza un test exacto y un test aproximado para la proporción verdadera.</strong></li>
</ul>
<p>El contraste que debemos realizar se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \pi = 0.2 \\
H_1: &amp; \pi &gt; 0.2 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>Como se verifica que <span class="math inline">\(n*\pi_0=169*0.2 = 33.8 &gt; 10\)</span> y <span class="math inline">\(n*(1-\pi_0)=169*0.8 = 135.2 &gt; 10\)</span>, podemos realizar el test aproximado como:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(x, n, <span class="at">p=</span><span class="fl">0.2</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  x out of n, null probability 0.2
X-squared = 0.81694, df = 1, p-value = 0.183
alternative hypothesis: true p is greater than 0.2
95 percent confidence interval:
 0.1792768 1.0000000
sample estimates:
        p 
0.2307692 </code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.183 &gt; \alpha=0.05 \Rightarrow\)</span> No rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, no podemos afirmar que la proporción de hombres con valores de hemoglobina glicosilada superior al 6% sea superior a 0.2.</p>
</section>
<section id="contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.05-si-la-proporción-de-hombres-con-colesterol-por-debajo-de-200mgdl-es-superior-a-la-proporción-de-mujeres-con-colesterol-por-debajo-de-200mgdl.">1.5. Contrasta al nivel de significación 0.05 si la proporción de hombres con colesterol por debajo de 200mg/dL es superior a la proporción de mujeres con colesterol por debajo de 200mg/dL.</h2>
<p>Definimos la variable:</p>
<p>X=“Nº de hombres con colesterol por debajo de 200mg/dL” <span class="math inline">\(\sim Bin(n_X,\pi_X)\)</span></p>
<p>Y=“Nº de mujeres con colesterol por debajo de 200mg/dL” <span class="math inline">\(\sim Bin(n_Y,\pi_Y)\)</span></p>
<ul>
<li><strong>Calcula el número de hombres en la muestra con colesterol por debajo de 200mg/dL y el total de hombres de la muestra (</strong><span class="math inline">\(n_X\)</span>).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>chol<span class="sc">&lt;</span><span class="dv">200</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>nx <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>nx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 169</code></pre>
</div>
</div>
<ul>
<li><strong>Calcula el número de mujeres en la muestra con colesterol por debajo de 200mg/dL y el total de mujeres de la muestra (</strong><span class="math inline">\(n_Y\)</span>).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span> <span class="sc">&amp;</span> diabetes<span class="sc">$</span>chol<span class="sc">&lt;</span><span class="dv">200</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ny <span class="ot">&lt;-</span> <span class="fu">sum</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ny</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 234</code></pre>
</div>
</div>
<ul>
<li><strong>Realiza un test para la diferencia de proporciones.</strong></li>
</ul>
<p>El contraste que debemos realizar se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \pi_X - \pi_Y = 0 \\
H_1: &amp; \pi_X - \pi_Y &gt; 0 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>Realizamos el test en R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(x,y), <span class="fu">c</span>(nx,ny), <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(x, y) out of c(nx, ny)
X-squared = 0.073608, df = 1, p-value = 0.3931
alternative hypothesis: greater
95 percent confidence interval:
 -0.06909495  1.00000000
sample estimates:
   prop 1    prop 2 
0.4674556 0.4487179 </code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.3931 &gt; \alpha=0.05 \Rightarrow\)</span> No rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, no podemos afirmar que la proporción de hombres con colesterol por debajo de 200mg/dL sea superior a la proporción de mujeres con colesterol por debajo de 200mg/dL.</p>
</section>
</section>
<section id="contrastes-no-paramétricos" class="level1">
<h1>2. Contrastes no-paramétricos</h1>
<section id="puede-asumirse-que-la-variable-hdl-en-mujeres-sigue-una-distribución-normal-contrasta-al-nivel-de-significación-0.05-si-la-media-de-la-variable-hdl-en-mujeres-es-superior-a-47." class="level2">
<h2 class="anchored" data-anchor-id="puede-asumirse-que-la-variable-hdl-en-mujeres-sigue-una-distribución-normal-contrasta-al-nivel-de-significación-0.05-si-la-media-de-la-variable-hdl-en-mujeres-es-superior-a-47.">2.1. ¿Puede asumirse que la variable ‘hdl’ en mujeres sigue una distribución normal? Contrasta al nivel de significación 0.05 si la media de la variable ‘hdl’ en mujeres es superior a 47.</h2>
<p>Sea X=“Nivel de HDL de las mujeres (mg/dL)”.</p>
<p>El contraste que debemos realizar (<span class="math inline">\(\alpha=0.05\)</span>) se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \mu=47 \\
H_1: &amp; \mu&gt;47 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>En primer lugar seleccionamos los datos de la muestra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>pos <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>hdl.female <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>hdl[pos]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Comprobamos la condición de normalidad:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(hdl.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 234.000    0.000   14.000   41.000   52.111   47.500   50.825   59.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 120.000   17.255  297.739    1.128   18.000  106.000    2.443    1.390 
SW p-val 
   0.000 </code></pre>
</div>
</div>
<p>Como no se verifica la normalidad (p-valor <span class="math inline">\(&lt;0.05\)</span>), realizamos el test no-paramétrico para una media (test de Wilcoxon):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(hdl.female, <span class="at">mu=</span><span class="dv">47</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  hdl.female
V = 16282, p-value = 0.001492
alternative hypothesis: true location is greater than 47</code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.0015 &lt; \alpha=0.05 \Rightarrow\)</span> Rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, existen evidencias estadísticas para afirmar que el nivel medio de HDL en mujeres es superior a 47 mg/dL.</p>
</section>
<section id="contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-entre-los-niveles-de-hdl-en-hombres-y-en-mujeres.-comprueba-si-puede-asumirse-normalidad-y-realiza-el-contraste-adecuado." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-entre-los-niveles-de-hdl-en-hombres-y-en-mujeres.-comprueba-si-puede-asumirse-normalidad-y-realiza-el-contraste-adecuado.">2.2. ¿Contrasta al nivel de significación 0.05 si existen diferencias entre los niveles de hdl en hombres y en mujeres. Comprueba si puede asumirse normalidad y realiza el contraste adecuado.</h2>
<p>Definimos las variables:</p>
<p>X=“Nivel de HDL en hombres (mg/dL)”</p>
<p>Y=“Nivel de HDL en mujeres (mg/dL)”</p>
<p>El contraste que debemos realizar (<span class="math inline">\(\alpha=0.10\)</span>) se escribe como: <span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \mu_X - \mu_Y = 0 \\
H_1: &amp; \mu_X - \mu_Y \neq 0 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>En primer lugar seleccionamos los datos de las muestras:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>pos1 <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"male"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>hdl.male <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>hdl[pos1]</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>pos2 <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>hdl.female <span class="ot">&lt;-</span> diabetes<span class="sc">$</span>hdl[pos2]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Comprobamos la condición de normalidad en ambas variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(hdl.male)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 169.000    0.000   12.000   35.000   48.139   44.000   47.173   59.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 117.000   17.004  289.141    1.308   24.000  105.000    1.001    0.934 
SW p-val 
   0.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(hdl.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
 234.000    0.000   14.000   41.000   52.111   47.500   50.825   59.000 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
 120.000   17.255  297.739    1.128   18.000  106.000    2.443    1.390 
SW p-val 
   0.000 </code></pre>
</div>
</div>
<p>En este caso no es necesario, pero podríamos verificar la igualdad de varianzas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(hdl <span class="sc">~</span> gender, <span class="at">data=</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como no se verifica la normalidad, realizamos el test no-paramétrico para la diferencia de medias (test de Mann-Withney):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(hdl.male, hdl.female, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  hdl.male and hdl.female
W = 16630, p-value = 0.006439
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.006&lt;\alpha=0.05 \Rightarrow\)</span> Rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, existen evidencias estadísticas para afirmar que el nivel medio de HDL en hombres y mujeres es distinto.</p>
</section>
<section id="considera-el-fichero-phenyl-de-la-libreria-paswr2.-contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-en-los-niveles-medios-de-la-coenzima-q10-en-el-momento-de-comenzar-el-estudio-variable-q10.1-y-al-finalizar-el-estudio-variable-q10.4." class="level2">
<h2 class="anchored" data-anchor-id="considera-el-fichero-phenyl-de-la-libreria-paswr2.-contrasta-al-nivel-de-significación-0.05-si-existen-diferencias-en-los-niveles-medios-de-la-coenzima-q10-en-el-momento-de-comenzar-el-estudio-variable-q10.1-y-al-finalizar-el-estudio-variable-q10.4.">2.3. Considera el fichero <code>PHENYL</code> de la libreria <code>PASWR2</code>. Contrasta al nivel de significación 0.05 si existen diferencias en los niveles medios de la coenzima Q10 en el momento de comenzar el estudio (variable <code>Q10.1</code>) y al finalizar el estudio (variable <code>Q10.4</code>).</h2>
<p>Definimos las variables:</p>
<p>X=“Nivel de coenzima Q10 al comienzo del estudio”</p>
<p>X=“Nivel de coenzima Q10 al final del estudio”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"PHENYL"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(PHENYL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Q10.1 Q10.2 Q10.3 Q10.4
1  0.39  0.56  0.65  0.45
2  0.33  0.32  0.44  0.37
3  0.59  0.58  0.38  0.55
4  0.86  0.51  0.53  0.47
5  0.33  0.29  0.29  0.28
6  0.49  0.37  0.33  0.39</code></pre>
</div>
</div>
<p>Como se tratan de los mismos individuos medidos en distintos instantes de tiempo, las muestras son dependientes (o emparejadas). Por lo tanto, trabajaremos con la diferencia entre ambas variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> PHENYL<span class="sc">$</span>Q10<span class="fl">.1</span><span class="sc">-</span>PHENYL<span class="sc">$</span>Q10<span class="fl">.4</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobamos la condición de normalidad</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">eda</span>(D)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Size (n)  Missing  Minimum   1st Qu     Mean   Median   TrMean   3rd Qu 
  46.000    0.000   -0.220   -0.048    0.122    0.100    0.120    0.298 
     Max    Stdev      Var  SE Mean   I.Q.R.    Range Kurtosis Skewness 
   0.470    0.190    0.036    0.028    0.346    0.690   -1.172    0.305 
SW p-val 
   0.022 </code></pre>
</div>
</div>
<p>El contraste que debemos realizar se escribe como:</p>
<p><span class="math display">\[\begin{eqnarray*}
\begin{array}{rl}
H_0: &amp; \mu_D = 0 \\
H_1: &amp; \mu_D \neq 0 \\
\end{array}
\end{eqnarray*}\]</span></p>
<p>Como no se verifica la hipótesis de normalidad, realizamo el test no-paramétrico para la diferencia de medias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(D, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(D, mu = 0, alternative = "two.sided"): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  D
V = 857.5, p-value = 0.0005439
alternative hypothesis: true location is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Otra opción</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(PHENYL<span class="sc">$</span>Q10<span class="fl">.1</span>, PHENYL<span class="sc">$</span>Q10<span class="fl">.4</span>, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">mu=</span><span class="dv">0</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(PHENYL$Q10.1, PHENYL$Q10.4, paired = TRUE, :
cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  PHENYL$Q10.1 and PHENYL$Q10.4
V = 857.5, p-value = 0.0005439
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Como p-valor<span class="math inline">\(=0.0005 &lt; \alpha=0.05 \Rightarrow\)</span> Rechazamos <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretación</strong>: Con un nivel de significación del 5%, tenemos evidencias estadísticas para afirmar que los niveles medios de la coenzima Q10 han cambiado a lo largo del estudio.</p>
</section>
</section>
<section id="análisis-de-la-varianza-y-test-de-kruskal-wallis" class="level1">
<h1>3. Análisis de la varianza y test de Kruskal-Wallis</h1>
<section id="contrasta-al-nivel-de-significación-0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.10-si-el-tamaño-del-cuerpo-frame-influye-en-la-presión-diastólica-bp.1d-de-las-mujeres.">3.1. Contrasta al nivel de significación 0.10 si el tamaño del cuerpo (<code>frame</code>) influye en la presión diastólica (<code>bp.1d</code>) de las mujeres.</h2>
<p><strong>a) Crea un nuevo fichero llamado <code>diabetes.female</code> solo con las mujeres.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>pos <span class="ot">&lt;-</span> <span class="fu">which</span>(diabetes<span class="sc">$</span>gender<span class="sc">==</span><span class="st">"female"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>diabetes.female <span class="ot">&lt;-</span> diabetes[pos,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>b) Exploración gráfica: representa los diagrama de caja de la variable <code>bp.1d</code> según la variable <code>frame</code>.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bp<span class="fl">.1</span>d <span class="sc">~</span> frame, <span class="at">data=</span>diabetes.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>c) Realiza el análisis de la varianza con la función <code>aov()</code></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">aov</span>(bp<span class="fl">.1</span>d <span class="sc">~</span> frame, <span class="at">data=</span>diabetes.female)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)  
frame         2    921   460.7   2.572 0.0786 .
Residuals   231  41376   179.1                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>d) Comprueba si pueden asumirse las hipótesis del modelo.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PASWR2)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">checking.plots</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test de normalidad para los errores</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">rstandard</span>(modelo)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(r)           </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  r
W = 0.98986, p-value = 0.1008</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Test de Levene para homogeneidad de varianzas</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(bp<span class="fl">.1</span>d <span class="sc">~</span> frame, <span class="at">data=</span>diabetes.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   2  1.8214 0.1641
      231               </code></pre>
</div>
</div>
<p><strong>e) Utiliza un test de Tukey para averiguar entre qué niveles de la variable <code>frame</code> existen diferencias significativas en los niveles medios de la variable <code>bp.1d</code></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>modelo.comp <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(modelo, <span class="at">conf.level=</span><span class="fl">0.9</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>modelo.comp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    90% family-wise confidence level

Fit: aov(formula = bp.1d ~ frame, data = diabetes.female)

$frame
                  diff       lwr        upr     p adj
medium-large  2.121373 -2.811945  7.0546917 0.6491061
small-large  -2.423910 -7.826310  2.9784887 0.6247892
small-medium -4.545284 -8.697193 -0.3933743 0.0639277</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Graficos de intervalos de confianza del test de Tukey</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo.comp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="utiliza-el-fichero-diabetes.female-para-responder-a-las-siguientes-cuestiones." class="level2">
<h2 class="anchored" data-anchor-id="utiliza-el-fichero-diabetes.female-para-responder-a-las-siguientes-cuestiones.">3.2. Utiliza el fichero <code>diabetes.female</code> para responder a las siguientes cuestiones.</h2>
<p><strong>a) Contrasta al nivel de significación</strong> <span class="math inline">\(\alpha=0.05\)</span> <strong>si existen diferencias entre los niveles medios de glucosa glicosilada (<code>glyhb</code>) según la constitución del tamaño del cuerpo (<code>frame</code>) entre las mujeres.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(glyhb <span class="sc">~</span> frame, <span class="at">data=</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>glyhb.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(glyhb<span class="sc">~</span>frame, <span class="at">data=</span>diabetes.female)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glyhb.aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value  Pr(&gt;F)   
frame         2   40.4  20.207     4.7 0.00998 **
Residuals   231  993.1   4.299                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobamos las hipótesis del modelo</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">checking.plots</span>(glyhb.aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practica3_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">rstandard</span>(glyhb.aov)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(r) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  r
W = 0.7235, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(glyhb.aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   2  1.0362 0.3564
      231               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Como no se cumplen las hipótesis del modelo, realizamos el test de Kruskal-Wallis</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(glyhb<span class="sc">~</span>frame, <span class="at">data=</span>diabetes.female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  glyhb by frame
Kruskal-Wallis chi-squared = 20.111, df = 2, p-value = 4.295e-05</code></pre>
</div>
</div>
<p><strong>b) Si has detectado diferencias, averigua entre qué grupos existen diferencias estadísticamente significativas.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal</span>(diabetes.female<span class="sc">$</span>glyhb, diabetes.female<span class="sc">$</span>frame, <span class="at">alpha=</span><span class="fl">0.05</span>, <span class="at">group=</span><span class="cn">FALSE</span>, <span class="at">console=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Study: diabetes.female$glyhb ~ diabetes.female$frame
Kruskal-Wallis test's
Ties or no Ties

Critical Value: 20.11077
Degrees of freedom: 2
Pvalue Chisq  : 4.295381e-05 

diabetes.female$frame,  means of the ranks

       diabetes.female.glyhb   r
large              157.07143  42
medium             114.76423 123
small               98.28986  69

Post Hoc Analysis

Comparison between treatments mean of the ranks.

               Difference pvalue Signif.       LCL      UCL
large - medium   42.30720 0.0003     *** 19.424803 65.18960
large - small    58.78157 0.0000     *** 33.723420 83.83973
medium - small   16.47437 0.0932       . -2.783587 35.73233</code></pre>
</div>
</div>
</section>
</section>
<section id="para-entregar" class="level1">
<h1>4. Para entregar</h1>
<p>Responde a las siguientes cuestiones, utilizando la misma muestra de pacientes que te ha sido asignada en la Práctica 2 para el fichero <code>patients.txt</code>.</p>
<section id="contrasta-al-nivel-de-significación-0.1-si-los-niveles-medios-de-la-concentración-de-interleukina-6-il6-son-significativamente-distintos-en-pacientes-con-cáncer-en-estadio-i-que-en-paciente-con-cáncer-en-estadio-ii." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-0.1-si-los-niveles-medios-de-la-concentración-de-interleukina-6-il6-son-significativamente-distintos-en-pacientes-con-cáncer-en-estadio-i-que-en-paciente-con-cáncer-en-estadio-ii.">4.1. Contrasta al nivel de significación 0.1 si los niveles medios de la concentración de Interleukina-6 (<code>IL6</code>) son significativamente distintos en pacientes con cáncer en estadio I que en paciente con cáncer en estadio II.</h2>
<ul>
<li><p>Define correctamente las variables del problema.</p></li>
<li><p>Comprueba si las dos muestras provienen de poblaciones normales.</p></li>
<li><p>Realiza el correspondiente test de hipótesis.</p></li>
</ul>
</section>
<section id="se-estudió-la-eficacia-de-la-sulfinpirazona-en-prevenir-la-muerte-después-de-sufrir-infarto-de-miocardio.-para-ello-se-consideraron-pacientes-que-habían-sufrido-infarto-de-miocardio.-a-un-grupo-se-les-proporcionó-sulfinpirazona-y-a-otro-grupo-se-les-suministró-placebo.-en-la-siguiente-tabla-se-muestra-el-número-de-pacientes-de-cada-grupo-que-murieron-y-que-superaron-el-infarto." class="level2">
<h2 class="anchored" data-anchor-id="se-estudió-la-eficacia-de-la-sulfinpirazona-en-prevenir-la-muerte-después-de-sufrir-infarto-de-miocardio.-para-ello-se-consideraron-pacientes-que-habían-sufrido-infarto-de-miocardio.-a-un-grupo-se-les-proporcionó-sulfinpirazona-y-a-otro-grupo-se-les-suministró-placebo.-en-la-siguiente-tabla-se-muestra-el-número-de-pacientes-de-cada-grupo-que-murieron-y-que-superaron-el-infarto.">4.2. Se estudió la eficacia de la sulfinpirazona en prevenir la muerte después de sufrir infarto de miocardio. Para ello se consideraron pacientes que habían sufrido infarto de miocardio. A un grupo se les proporcionó sulfinpirazona y a otro grupo se les suministró placebo. En la siguiente tabla se muestra el número de pacientes de cada grupo que murieron y que superaron el infarto.</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Death (all causes)</th>
<th>Survivors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sulphinpyrazole</td>
<td>41</td>
<td>692</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td>60</td>
<td>682</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Contrasta al nivel de significación</strong> <span class="math inline">\(\alpha=0.01\)</span> si la proporción de muertes de pacientes que tomaron sulfinpirazona es inferior a la de pacientes que tomaron un placebo.</li>
</ul>
</section>
<section id="contrasta-al-nivel-de-significación-alpha0.1-si-existen-diferencias-en-la-edad-media-de-los-pacientes-según-el-estadio-de-cancer-cancerstage." class="level2">
<h2 class="anchored" data-anchor-id="contrasta-al-nivel-de-significación-alpha0.1-si-existen-diferencias-en-la-edad-media-de-los-pacientes-según-el-estadio-de-cancer-cancerstage.">4.3. Contrasta al nivel de significación <span class="math inline">\(\alpha=0.1\)</span> si existen diferencias en la edad media de los pacientes según el estadio de cancer (<code>CancerStage</code>).</h2>
<ul>
<li><p><strong>Realiza una exploración gráfica y el análisis de varianza correspondiente</strong></p></li>
<li><p><strong>Comprueba si pueden asumirse las hipótesis del modelo</strong></p></li>
<li><p><strong>Si has detectado diferencias, averigua entre qué grupos existen diferencias estadísticamente significativas</strong></p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>